export enum UserType {
  CENTER_REGISTRAR = "CENTER_REGISTRAR",
  CASE_MANAGER = "CASE_MANAGER",
  HEAD_ADR_OPERATIONS = "HEAD_ADR_OPERATIONS",
  HEAD_NEUTRAL_PROG_TRAINING = "HEAD_NEUTRAL_PROG_TRAINING",
  MEDIATOR = "MEDIATOR",
  MENTEE = "MENTEE",
  DIRECTOR = "DIRECTOR",

  LAWYER = "LAWYER",
  INDIVIDUAL = "INDIVIDUAL",
}
